package app

import (
	"context"
	"database/sql"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	_ "github.com/mattn/go-sqlite3"

	"Graft/internal/admin"
	"Graft/internal/config"
	"Graft/internal/connectors"
	"Graft/internal/engine"
	"Graft/internal/forwarder"
	"Graft/internal/httpapi"
	"Graft/internal/observability"
	"Graft/internal/router"
	"Graft/internal/server"
	"Graft/internal/storage"
)

// Run loads configuration, wires dependencies, and blocks serving HTTP.
func Run() error {
	printBanner() // Welcome developers!

	cfg, err := config.Load()
	if err != nil {
		return err
	}

	// Initialize observability logging
	observabilityConfig := observability.Config{
		Enabled:     cfg.AuditEnabled,
		FilePath:    cfg.AuditFilePath,
		MinSeverity: cfg.AuditMinSeverity,
	}
	observabilityLogger, err := observability.NewLogger(observabilityConfig)
	if err != nil {
		return fmt.Errorf("observability logger: %w", err)
	}
	defer observabilityLogger.Close()
	observability.SetDefaultLogger(observabilityLogger)

	db, err := sql.Open("sqlite3", cfg.DBPath)
	if err != nil {
		return fmt.Errorf("open database: %w", err)
	}
	defer db.Close()

	if err := db.Ping(); err != nil {
		return fmt.Errorf("ping database: %w", err)
	}

	repo, err := storage.NewSQLiteRepo(db, cfg.MasterKey)
	if err != nil {
		return fmt.Errorf("repository: %w", err)
	}

	httpFwd := connectors.NewHTTPForwarder(connectors.HTTPConfig{
		Timeout:       cfg.ForwardTimeout,
		MaxRetries:    cfg.ForwardMaxRetries,
		BaseRetryWait: cfg.ForwardRetryBase,
	})
	fwd := forwarder.NewSyncForwarder(httpFwd)

	// --- Initialize Native Connector Registry ---
	var emailConnector *connectors.EmailConnector
	if cfg.SMTPHost != "" {
		emailConnector = connectors.NewEmailConnector(
			cfg.SMTPHost,
			cfg.SMTPUsername,
			cfg.SMTPPassword,
			cfg.SMTPFrom,
		)
	}
	registry := connectors.NewRegistry(emailConnector)

	eng := engine.New(repo, cfg.MasterKey, fwd, registry)
	admService := admin.NewService(repo, cfg.MasterKey)

	// Phase 1: Initialize Queue and Worker Pool
	queue := engine.NewMemoryQueue(cfg.QueueSize)
	workerPool := engine.NewWorkerPool(queue, eng, cfg.WorkerCount)
	workerPool.Start(context.Background())

	wh := httpapi.NewWebhookHandler(eng, queue)
	adminH := httpapi.NewAdminHandler(admService, eng)
	adminMux := http.NewServeMux()
	adminH.Register(adminMux)

	// Build security middleware chain
	secConfig := router.BuildSecurityConfig(cfg)

	root := router.NewRootMux(router.Config{
		WebhookHandler: wh,
		AdminInner:     adminMux,
		AdminAPIKey:    cfg.AdminAPIKey,
		Security:       secConfig,
	})

	// Load TLS configuration if enabled
	tlsConfig, err := server.LoadTLSConfig(server.TLSConfig{
		Enabled:         cfg.TLSEnabled,
		CertFile:        cfg.TLSCertFile,
		KeyFile:         cfg.TLSKeyFile,
		AutoGenerate:    cfg.TLSAutoGen,
		AutoGenerateDir: cfg.TLSAutoGenDir,
	})
	if err != nil {
		return fmt.Errorf("tls config: %w", err)
	}

	srv := server.NewHTTPServer(cfg, root, tlsConfig)

	go func() {
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			slog.Error("Failed to listen", "error", err)
			os.Exit(1)
		}
	}()

	protocol := "http"
	if srv.IsTLS() {
		protocol = "https"
	}

	slog.Info("Server listening", "port", cfg.Port, "tls", srv.IsTLS())
	observability.Default().Log(observability.Event{
		Timestamp: time.Now(),
		Type:      observability.EventStartup,
		Severity:  observability.SeverityInfo,
	})

	fmt.Printf("\n🚀 Graft Webhook Bridge successfully started!\n\n")
	fmt.Printf("   Dashboard & Health :	 %s://localhost:%s/\n", protocol, cfg.Port)
	fmt.Printf("   Admin API Base     :	 %s://localhost:%s/api/v1/\n", protocol, cfg.Port)
	fmt.Printf("   Webhook Listen Path:	 %s://localhost:%s/hook/{path}\n\n", protocol, cfg.Port)

	if cfg.DevMode {
		fmt.Printf("⚠️  DEV MODE: Security headers relaxed, review before production!\n\n")
	} else if !cfg.TLSEnabled {
		fmt.Printf("⚠️  WARNING: TLS not enabled. Set TLS_ENABLED=1 for production!\n\n")
	}

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, os.Interrupt, syscall.SIGTERM)
	<-quit

	slog.Info("Shutting down server...")
	observability.Default().Log(observability.Event{
		Timestamp: time.Now(),
		Type:      observability.EventShutdown,
		Severity:  observability.SeverityInfo,
	})

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if err := srv.Shutdown(ctx); err != nil {
		return fmt.Errorf("server shutdown: %w", err)
	}

	workerPool.Stop()

	slog.Info("Server exited gracefully")
	return nil
}

// printBanner displays the application's logo and branding.
func printBanner() {
	banner := `
   _____            __ _
  / ____|          / _| |
 | |  __ _ __ __ _| |_| |_
 | | |_ | '__/ _` + "`" + ` |  _| __|
 | |__| | | | (_| | | | |_
  \_____|_|  \__,_|_|  \__|

  A Self-Hosted Webhook Bridge
================================
`
	fmt.Print(banner)
}
